version: "3.7"
services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: P@ssword
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
