version: "3.7"
services:
  postgres:
    image: postgres:13
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_DB: discount
      POSTGRES_USER: discount
      POSTGRES_PASSWORD: P@ssword
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data

  migration:
    image: migrate/migrate:v4.14.1
    command: ["-path=/migrations", "-database=postgres://discount:P@ssword@postgres:5432/discount?sslmode=disable", "up"]
    restart: on-failure
    volumes:
      - ./infrastructure/migrations:/migrations
