version: "3.7"
services:
  postgres_inventory:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: inventory
      POSTGRES_PASSWORD: P@ssword
    volumes:
      - ./.docker/postgres_inventory/data:/var/lib/postgresql/data

  postgres_discount:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: discount
      POSTGRES_USER: discount
      POSTGRES_PASSWORD: P@ssword
    volumes:
      - ./.docker/postgres_discount/data:/var/lib/postgresql/data

  postgres_inventory_migration:
    image: migrate/migrate:v4.14.1
    command: ["-path=/migrations", "-database=postgres://inventory:P@ssword@postgres_inventory:5432/inventory?sslmode=disable", "up"]
    restart: on-failure
    volumes:
      - ../inventory/infrastructure/migrations:/migrations

  postgres_discount_migration:
    image: migrate/migrate:v4.14.1
    command: ["-path=/migrations", "-database=postgres://discount:P@ssword@postgres_discount:5432/discount?sslmode=disable", "up"]
    restart: on-failure
    volumes:
      - ../discount/infrastructure/migrations:/migrations

  inventory:
    image: inventory:1.0.0
    restart: always
    environment:
      RPC_ADDRESS: :50052
      DB_USER: inventory
      DB_PASSWORD: P@ssword
      DB_HOST: postgres_inventory
      DB_PORT: 5432
      DB_DATABASE: inventory

  discount:
    image: discount:1.0.0
    restart: always
    environment:
      RPC_ADDRESS: :50051
      DB_USER: discount
      DB_PASSWORD: P@ssword
      DB_HOST: postgres_discount
      DB_PORT: 5432
      DB_DATABASE: discount

  online_shopping:
    image: online_shopping:1.0.0
    restart: always
    ports:
      - "8080:8080"
    environment:
      INVENTORY_ADDR: inventory:50052
      DISCOUNT_CALCULATOR_ADDR: discount:50051
      WEB_SERVER_PORT: 8080